resources:
  - url: http://127.0.0.1:5000/space-hub-card.js
    type: module
views:
  - cards:
      - type: custom:space-hub-card
        name: Space Hub Card Development
        entity: sun.sun
        test_gui: true
